// <auto-generated />
using System;
using DefaultProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DefaultProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DefaultProject.Models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<int?>("messageid");

                    b.Property<string>("text")
                        .IsRequired();

                    b.Property<DateTime>("updated_at");

                    b.Property<int?>("userid");

                    b.HasKey("id");

                    b.HasIndex("messageid");

                    b.HasIndex("userid");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("DefaultProject.Models.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("text")
                        .IsRequired();

                    b.Property<DateTime>("updated_at");

                    b.Property<int?>("userid");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("DefaultProject.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("confirm_password");

                    b.Property<DateTime>("created_at");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("first_name")
                        .IsRequired();

                    b.Property<string>("last_name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DefaultProject.Models.Comment", b =>
                {
                    b.HasOne("DefaultProject.Models.Message", "message")
                        .WithMany("comments")
                        .HasForeignKey("messageid");

                    b.HasOne("DefaultProject.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid");
                });

            modelBuilder.Entity("DefaultProject.Models.Message", b =>
                {
                    b.HasOne("DefaultProject.Models.User", "user")
                        .WithMany("messages")
                        .HasForeignKey("userid");
                });
#pragma warning restore 612, 618
        }
    }
}
