// <auto-generated />
using System;
using DefaultProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DefaultProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DefaultProject.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("name");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("DefaultProject.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<int?>("customerid");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.HasIndex("customerid");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("DefaultProject.Models.OrderProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<int>("orderId");

                    b.Property<int>("productId");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.HasIndex("orderId");

                    b.HasIndex("productId");

                    b.ToTable("orders_products");
                });

            modelBuilder.Entity("DefaultProject.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<string>("description");

                    b.Property<string>("name");

                    b.Property<int>("quantity");

                    b.Property<DateTime>("updated_at");

                    b.Property<string>("url");

                    b.HasKey("id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("DefaultProject.Models.Order", b =>
                {
                    b.HasOne("DefaultProject.Models.Customer", "customer")
                        .WithMany("orders")
                        .HasForeignKey("customerid");
                });

            modelBuilder.Entity("DefaultProject.Models.OrderProduct", b =>
                {
                    b.HasOne("DefaultProject.Models.Order", "order")
                        .WithMany()
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DefaultProject.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
