// <auto-generated />
using System;
using DefaultProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DefaultProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20180717181110_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DefaultProject.Models.RSVP", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("created_at");

                    b.Property<DateTime>("updated_at");

                    b.Property<int?>("userid");

                    b.Property<int?>("weddingid");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.HasIndex("weddingid");

                    b.ToTable("rsvps");
                });

            modelBuilder.Entity("DefaultProject.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("confirm_password");

                    b.Property<DateTime>("created_at");

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("first_name")
                        .IsRequired();

                    b.Property<string>("last_name")
                        .IsRequired();

                    b.Property<string>("password")
                        .IsRequired();

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DefaultProject.Models.Wedding", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address")
                        .IsRequired();

                    b.Property<DateTime>("created_at");

                    b.Property<int?>("creatorid");

                    b.Property<DateTime>("date");

                    b.Property<DateTime>("updated_at");

                    b.Property<string>("wedder1")
                        .IsRequired();

                    b.Property<string>("wedder2")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("creatorid");

                    b.ToTable("weddings");
                });

            modelBuilder.Entity("DefaultProject.Models.RSVP", b =>
                {
                    b.HasOne("DefaultProject.Models.User", "user")
                        .WithMany("rsvps")
                        .HasForeignKey("userid");

                    b.HasOne("DefaultProject.Models.Wedding", "wedding")
                        .WithMany("rsvps")
                        .HasForeignKey("weddingid");
                });

            modelBuilder.Entity("DefaultProject.Models.Wedding", b =>
                {
                    b.HasOne("DefaultProject.Models.User", "creator")
                        .WithMany("weddings")
                        .HasForeignKey("creatorid");
                });
#pragma warning restore 612, 618
        }
    }
}
